version: '3.9'

services:
  selenium:
    # CPUアーキテクチャがx86_64の場合は下記のみをコメントイン
    image: selenium/standalone-chrome:latest
    # CPUアーキテクチャがarmの場合下記はのみをコメントイン
    # image: seleniarm/standalone-chromium:latest
    shm_size: "2g"
    container_name: 'selenium'
    ports:
      - "4444:4444"
      - "5900:5900"
